export const types = {
  GET_ALL_PROPERTIES: "GET_ALL_PROPERTIES",
  GET_MORE_PROPERTIES: "GET_MORE_PROPERTIES",
  LOGIN_USER: "LOGIN_USER",
  SIGNUP_USER: "SIGNUP_USER",
  PROPERTY_DETAILS: "PROPERTY_DETAILS",
  GET_SEARCH_PROPERTIES:"GET_SEARCH_PROPERTIES",
  EDIT_USER: "EDIT_USER",
  GET_WISHLIST:"GET_WISHLIST",
  ADD_WISHLIST:"ADD_WISHLIST"
};
